import "@/app/globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Ubuntu as Inter  } from "next/font/google"

import { cn } from "@/lib/utils"

export const inter = Inter({
  subsets: ["latin"],
  weight: ['300', '400', '500', '700']
})


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={
          "min-h-screen bg-background font-sans antialiased " +
          inter.className
        }
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            className = {inter.className}
            // enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
